/**
 * Level catalogue.
 *
 * Levels are authored as data (`src/levels/NN.json`, generated by
 * `scripts/gen_levels.mjs`) so the curve can be retuned without touching code.
 * Because JSON carries no type information, everything is validated here on load
 * and surfaced as a fully-typed `LevelDef`. A malformed level fails loudly at
 * startup rather than producing a subtly unplayable board.
 */

import type { CrystalColor, LevelDef, Objective, ObjectiveKind } from '@engine/types';
import { CRYSTAL_COLORS } from '@engine/types';

const OBJECTIVE_KINDS: readonly ObjectiveKind[] = [
  'score',
  'crust',
  'collect',
  'defuse',
  'contain',
];

/** Characters permitted in a `layout` row. */
const LAYOUT_CHARS = new Set(['.', '#', '1', '2', '3', 'S', 'B', 'R']);

class LevelError extends Error {
  constructor(file: string, msg: string) {
    super(`level ${file}: ${msg}`);
    this.name = 'LevelError';
  }
}

const isRecord = (v: unknown): v is Record<string, unknown> =>
  typeof v === 'object' && v !== null && !Array.isArray(v);

function validate(file: string, raw: unknown): LevelDef {
  const fail = (msg: string): never => {
    throw new LevelError(file, msg);
  };

  if (!isRecord(raw)) return fail('not an object');

  const num = (k: string): number => {
    const v = raw[k];
    if (typeof v !== 'number' || !Number.isFinite(v)) return fail(`"${k}" must be a number`);
    return v;
  };

  const id = num('id');
  const width = num('width');
  const height = num('height');
  const moves = num('moves');

  if (width < 3 || height < 3) fail('board must be at least 3x3');
  if (moves < 1) fail('moves must be positive');

  const rawName = raw['name'];
  if (typeof rawName !== 'string' || rawName.length === 0) {
    return fail('"name" must be a non-empty string');
  }
  const name: string = rawName;

  // -- colours --------------------------------------------------------------
  const rawColors = raw['colors'];
  if (!Array.isArray(rawColors) || rawColors.length < 3) {
    fail('"colors" must list at least 3 colours');
  }
  const colors = (rawColors as unknown[]).map((c) => {
    if (typeof c !== 'string' || !(CRYSTAL_COLORS as readonly string[]).includes(c)) {
      return fail(`unknown colour ${JSON.stringify(c)}`);
    }
    return c as CrystalColor;
  });

  // -- objectives -----------------------------------------------------------
  const rawObjectives = raw['objectives'];
  if (!Array.isArray(rawObjectives) || rawObjectives.length === 0) {
    fail('"objectives" must be a non-empty array');
  }
  const objectives: Objective[] = (rawObjectives as unknown[]).map((o) => {
    if (!isRecord(o)) return fail('objective is not an object');
    const kind = o['kind'];
    if (typeof kind !== 'string' || !(OBJECTIVE_KINDS as readonly string[]).includes(kind)) {
      return fail(`unknown objective kind ${JSON.stringify(kind)}`);
    }
    const target = o['target'];
    if (typeof target !== 'number' || target <= 0) {
      return fail(`objective "${kind}" needs a positive target`);
    }
    const color = o['color'];
    if (color !== undefined && !(CRYSTAL_COLORS as readonly string[]).includes(color as string)) {
      return fail(`objective "${kind}" has unknown colour ${JSON.stringify(color)}`);
    }
    return {
      kind: kind as ObjectiveKind,
      target,
      ...(color !== undefined ? { color: color as CrystalColor } : {}),
    };
  });

  // -- stars ----------------------------------------------------------------
  const rawStars = raw['stars'];
  if (!Array.isArray(rawStars) || rawStars.length !== 3) fail('"stars" must have exactly 3 entries');
  const stars = (rawStars as unknown[]).map((s) => {
    if (typeof s !== 'number' || s <= 0) return fail('star thresholds must be positive numbers');
    return s;
  }) as [number, number, number];
  if (!(stars[0] < stars[1] && stars[1] < stars[2])) fail('star thresholds must ascend');

  // -- layout ---------------------------------------------------------------
  let layout: string[] | undefined;
  const rawLayout = raw['layout'];
  if (rawLayout !== undefined) {
    if (!Array.isArray(rawLayout)) fail('"layout" must be an array of strings');
    const rows = rawLayout as unknown[];
    if (rows.length !== height) fail(`layout has ${rows.length} rows, expected ${height}`);
    layout = rows.map((row, y) => {
      if (typeof row !== 'string') return fail(`layout row ${y} is not a string`);
      if (row.length !== width) {
        return fail(`layout row ${y} is ${row.length} wide, expected ${width}`);
      }
      for (const ch of row) {
        if (!LAYOUT_CHARS.has(ch)) return fail(`layout row ${y} has illegal char ${JSON.stringify(ch)}`);
      }
      return row;
    });

    // A level whose goal is unreachable from its own board is a content bug.
    const count = (pred: (c: string) => boolean) =>
      layout!.reduce((n, r) => n + [...r].filter(pred).length, 0);

    const playable = count((c) => c !== '#');
    if (playable < 9) fail('fewer than 9 playable cells');

    for (const o of objectives) {
      if (o.kind === 'crust') {
        const crust = count((c) => c === '1' || c === '2' || c === '3');
        if (crust !== o.target) fail(`crust objective targets ${o.target} but layout has ${crust} crusted cells`);
      }
      if (o.kind === 'defuse') {
        const bombs = count((c) => c === 'B');
        if (bombs !== o.target) fail(`defuse objective targets ${o.target} but layout has ${bombs} bombs`);
      }
    }
  } else {
    for (const o of objectives) {
      if (o.kind === 'crust') fail('crust objective requires a layout');
      if (o.kind === 'defuse') fail('defuse objective requires a layout');
    }
  }

  const optNum = (k: string): number | undefined => {
    const v = raw[k];
    if (v === undefined) return undefined;
    if (typeof v !== 'number' || v <= 0) return fail(`"${k}" must be a positive number`);
    return v;
  };

  const shadowPeriod = optNum('shadowPeriod');
  const bombFuse = optNum('bombFuse');

  if (objectives.some((o) => o.kind === 'contain') && shadowPeriod === undefined) {
    fail('contain objective requires "shadowPeriod"');
  }
  if (layout?.some((r) => r.includes('B')) && bombFuse === undefined) {
    fail('layout places bombs but no "bombFuse" is set');
  }

  return {
    id,
    name,
    width,
    height,
    moves,
    objectives,
    stars,
    colors,
    ...(layout ? { layout } : {}),
    ...(shadowPeriod !== undefined ? { shadowPeriod } : {}),
    ...(bombFuse !== undefined ? { bombFuse } : {}),
  };
}

const modules = import.meta.glob<unknown>('./*.json', { eager: true, import: 'default' });

/** Every level, validated, ordered by id. */
export const LEVELS: readonly LevelDef[] = Object.entries(modules)
  .map(([path, raw]) => validate(path.replace('./', ''), raw))
  .sort((a, b) => a.id - b.id);

if (LEVELS.length === 0) throw new Error('no levels found in src/levels/');

LEVELS.forEach((lvl, i) => {
  if (lvl.id !== i + 1) {
    throw new Error(`level ids must be contiguous from 1; found ${lvl.id} at position ${i + 1}`);
  }
});

export const LEVEL_COUNT = LEVELS.length;

export const getLevel = (id: number): LevelDef => {
  const lvl = LEVELS[id - 1];
  if (!lvl) throw new Error(`no such level: ${id}`);
  return lvl;
};

/**
 * Levels where the curve deliberately steepens. These are the points a
 * free-to-play title applies economic pressure, and where the Publisher Dashboard
 * expects to see conversion events cluster. Documented in docs/ECONOMY.md.
 */
export const PRESSURE_POINTS: readonly number[] = [8, 15, 22, 28, 30, 35, 40];
