/**
 * Default theme pack — Crystalline (crystal-mine IP). Existing product surface.
 */

import type { ThemeConfig } from './types';
import { ALBUM_CARDS, ALBUM_SHEET } from '@economy/album';
import { META_STAGES, META_UPGRADES } from '@economy/meta';

export const crystallineTheme: ThemeConfig = {
  id: 'crystalline',
  productName: 'Crystalline',
  tagline: 'Match gems. Forge power. Furnish the living mine.',
  storagePrefix: 'crystalline',
  saveKey: 'crystalline.save',
  ahaKey: 'crystalline.ahaDone',
  adShortKey: 'crystalline.adShortIndex',
  softCurrencyName: 'Essence',
  softCurrencyGlyph: '✧',
  premiumCurrencyName: 'Shards',
  metaHubName: 'Crystal Cavern',
  metaHubCta: 'Your Cavern',
  assetRoot: '',
  bgPath: 'bg/mine-cavern-720.webp',
  genManifestPath: 'gen/manifest.json',
  albumSheet: ALBUM_SHEET,
  livingCorePath: 'gen/living_core.webp',
  companion: {
    id: 'geode-warden',
    name: 'Geode Warden',
    role: 'Cavern guide',
    art: 'characters/geode-warden.webp',
    lines: {
      title: [
        'The mountain remembers your steps. Dive when ready.',
        'Match, forge, furnish — I keep the lamps lit.',
        'A clear board feeds the cavern. Shall we?',
      ],
      titleFirst: [
        'First light in the mine. Swap four to forge a power.',
        'Welcome, prospector. I will show you the veins.',
      ],
      win: [
        'Clean cut! Essence drips into the cavern.',
        'The galleries hum for you — well dug.',
        'Another chamber yields. Onward, carefully.',
      ],
      winPerfect: [
        'Three stars — the geode sings. Discovery bonus sealed.',
        'Flawless work. The Deep will hear of this.',
      ],
      lose: [
        'The vein closed early. Breathe — lives return.',
        'Almost. The rock is patient; so are we.',
        'Not this path. Try another cut.',
      ],
      daily: [
        'A daily parcel from the guild. Claim it, friend.',
        'Welcome back. The mine left you a stipend.',
      ],
      cavern: [
        'Place what you can afford — the vista grows with you.',
        'Furnish the open stage. Ghost slots mark what is next.',
      ],
      cavernReady: [
        'You can place a piece right now. Look at the shop below.',
        'Essence is ready — seal it into the chamber.',
      ],
      geode: [
        'Tap a sealed geode. One hides a richer crack.',
        'Three veins. Trust your pick — I will not spoil it.',
      ],
      geodeResult: [
        'Sparkles for the cavern fund!',
        'A fine crack. Bank it and keep diving.',
        'Jackpot vein! The Warden is impressed.',
      ],
      coreSpire: [
        'Core Spire — the mountain’s spine. Conveyors never sleep.',
        'Deep chambers. Steady hands. I am with you still.',
      ],
      streak: [
        'The streak holds. Don’t rush the rock.',
        'Heat in the lamp glass — keep the chain clean.',
      ],
    },
  },
  metaStages: META_STAGES,
  metaUpgrades: META_UPGRADES,
  albumCards: ALBUM_CARDS,
  mapChapters: [
    { roman: 'I', title: 'Mouth of the Mine', depth: 'shallow', minId: 1, maxId: 10 },
    { roman: 'II', title: 'Prism Gallery', depth: 'mid', minId: 11, maxId: 20 },
    { roman: 'III', title: 'Deep Geode', depth: 'deep', minId: 21, maxId: 30 },
    { roman: 'IV', title: 'Core Spire', depth: 'core', minId: 31, maxId: 40 },
    { roman: 'V', title: 'Fault Line', depth: 'deep', minId: 41, maxId: 50 },
    { roman: 'VI', title: 'Buried Crown', depth: 'deep', minId: 51, maxId: 60 },
    { roman: 'VII', title: 'Void Gallery', depth: 'core', minId: 61, maxId: 70 },
    { roman: 'VIII', title: 'Living Heart', depth: 'core', minId: 71, maxId: 80 },
    { roman: 'IX', title: 'Eternal Mine', depth: 'core', minId: 81, maxId: 90 },
    { roman: 'X', title: 'Apex Crystal', depth: 'core', minId: 91, maxId: 100 },
    { roman: 'XI', title: 'Under-Vein', depth: 'deep', minId: 101, maxId: 110 },
    { roman: 'XII', title: 'Glass Root', depth: 'deep', minId: 111, maxId: 120 },
    { roman: 'XIII', title: 'Black Gallery', depth: 'core', minId: 121, maxId: 130 },
    { roman: 'XIV', title: 'Crown Depths', depth: 'core', minId: 131, maxId: 140 },
    { roman: 'XV', title: 'Regent Peak', depth: 'core', minId: 141, maxId: 150 },
    // Act I-C Under-Crown (docs/CAMPAIGN_ARC.md XVI–XXX)
    { roman: 'XVI', title: 'Crownroot Gate', depth: 'deep', minId: 151, maxId: 160 },
    { roman: 'XVII', title: 'Fault Lantern', depth: 'deep', minId: 161, maxId: 170 },
    { roman: 'XVIII', title: 'Echo Vein', depth: 'core', minId: 171, maxId: 180 },
    { roman: 'XIX', title: 'Glass Fault', depth: 'core', minId: 181, maxId: 190 },
    { roman: 'XX', title: 'Under-Crown', depth: 'core', minId: 191, maxId: 200 },
    { roman: 'XXI', title: 'Silent Gallery', depth: 'deep', minId: 201, maxId: 210 },
    { roman: 'XXII', title: 'Double Seam', depth: 'deep', minId: 211, maxId: 220 },
    { roman: 'XXIII', title: 'Black Heartwalk', depth: 'core', minId: 221, maxId: 230 },
    { roman: 'XXIV', title: 'Spire Answer', depth: 'core', minId: 231, maxId: 240 },
    { roman: 'XXV', title: 'Regent Approach', depth: 'core', minId: 241, maxId: 250 },
    { roman: 'XXVI', title: 'Crown War', depth: 'core', minId: 251, maxId: 260 },
    { roman: 'XXVII', title: 'Living Answer', depth: 'core', minId: 261, maxId: 270 },
    { roman: 'XXVIII', title: 'Mountain Voice', depth: 'core', minId: 271, maxId: 280 },
    { roman: 'XXIX', title: 'Last Gallery', depth: 'core', minId: 281, maxId: 290 },
    { roman: 'XXX', title: 'Under-Crown Close', depth: 'core', minId: 291, maxId: 300 },
  ],
  storeCopy: {},
  palette: {
    ember: '#ad4457',
    aurum: '#bd7032',
    solar: '#ae8d45',
    verdant: '#357a65',
    tidal: '#3e7ab3',
    void: '#94529a',
  },
  labels: {
    powerCrystal: 'Power Crystal',
    livingCore: 'Living Core',
    conveyorActive: 'Conveyor row active',
    slowBelt: 'Slow the belt',
    idleClaim: 'Cavern idle',
    bonusCrack: 'Geode crack',
    eventName: 'Mine Rush',
    dailyGoal: 'Daily dive',
    albumTitle: 'Endless Album',
    playCta: 'DIVE',
    mapTitle: 'The Mine',
  },
  // Finished-product surface tokens (parity with Harbor menu chrome).
  cssVars: {
    '--bg': '#0a0714',
    '--panel': '#18122e',
    '--panel-2': '#221a3c',
    '--panel-edge': '#c9a227',
    '--panel-edge-hi': '#ffd24a',
    '--text': '#fff6e8',
    '--muted': '#b0a8c8',
    '--accent': '#7ed0ff',
    '--accent-deep': '#3a6a9a',
    '--gold': '#ffd24a',
    '--gold-deep': '#c9a227',
    '--danger': '#ff7a8a',
    '--ok': '#7ec8a3',
    '--sim': '#ff9a62',
    '--font-title': '"DragonBlaze", "Cinzel", "ScreenTechno", serif',
    '--font-display': '"Fredoka", "ScreenTechno", system-ui, sans-serif',
    '--font-body': '"Nunito", "Segoe UI", system-ui, sans-serif',
    '--map-home-bg': 'linear-gradient(180deg, rgba(36, 24, 64, 0.94), rgba(14, 10, 28, 0.96))',
    '--map-home-edge': 'rgba(201, 162, 39, 0.4)',
    '--place-scrim':
      'linear-gradient(90deg, rgba(12, 8, 24, 0.9) 0%, rgba(12, 8, 24, 0.5) 55%, rgba(12, 8, 24, 0.22) 100%)',
  },
  bonusCrackName: 'Geode',
  bonusCrackArt: 'ui/geode_vein.webp',
  versionLabel: 'Crystalline v1.0.2 · 300 levels · Departure Bay Digital',
  powerNames: {
    line: 'Seam Rift',
    burst: 'Geode Burst',
    prism: 'Opal Prism',
    /** 6+ match Living Geode — crack + prism rays (not Harbor octopus). */
    supernova: 'Living Geode',
  },
  comboLabels: {},
  event: {
    idPrefix: 'mine-rush',
    name: 'Mine Rush',
    tagline: 'Clear chambers for personal milestones · soft league for flavour',
    milestones: [
      { at: 3, label: 'First seam', essence: 20, shards: 5 },
      { at: 8, label: 'Deep cut', essence: 35, shards: 10 },
      { at: 15, label: 'Gallery clear', essence: 50, shards: 15 },
      { at: 25, label: 'Vault push', essence: 80, shards: 25 },
    ],
    league: ['Crystal Elite', 'Vein Patrol', 'Prospectors'],
  },
  // No shared placement reel — the old place.webm always showed the crystal lamp
  // first, then the real prop. Ceremony is stage still + the purchased item only.
  placeCeremony: {
    webm: '',
    mp4: '',
    caption: 'Placed in the mine',
  },
};
