/**
 * Lantern Harbor — cozy coastal theme pack (sibling product).
 * All art under public/themes/harbor/. Engine color ids unchanged.
 */

import type { ThemeConfig } from './types';
import type { AlbumCardDef } from '@economy/album';
import type { MetaStage, MetaUpgrade } from '@economy/meta';

const R = 'themes/harbor/';
const icon = (file: string) => `${R}diorama/icons/${file}.webp`;

const F = (x: number, y: number) =>
  ({ x, y, w: 128, h: 128 }) as const;

const META_STAGES: readonly MetaStage[] = [
  {
    id: 1,
    name: 'Pier Lights',
    tagline: 'Light the first lanterns and claim the pier.',
    art: `${R}diorama/stages/stage1.webp`,
  },
  {
    id: 2,
    name: 'Market Row',
    tagline: 'Stalls hum with tea, crates, and evening trade.',
    art: `${R}diorama/stages/stage2.webp`,
  },
  {
    id: 3,
    name: 'Lighthouse Yard',
    tagline: 'Where the beacon still remembers the fog.',
    art: `${R}diorama/stages/stage3.webp`,
  },
  {
    id: 4,
    name: 'Night Festival',
    tagline: 'A canopy of lanterns only the stubborn reach.',
    art: `${R}diorama/stages/stage4.webp`,
  },
  // Act I-C Outer Channels — dedicated vistas + props
  {
    id: 5,
    name: 'Outer Channel',
    tagline: 'Beyond the festival — the tide rewrites the night.',
    art: `${R}diorama/stages/stage5.webp`,
  },
  {
    id: 6,
    name: 'Storm Treaty Quay',
    tagline: 'Where rival lanterns and fog fleets meet the docks.',
    art: `${R}diorama/stages/stage6.webp`,
  },
  {
    id: 7,
    name: 'Quiet Slip Reach',
    tagline: 'Fog berths and twin tides past the first treaty.',
    art: `${R}diorama/stages/stage7.webp`,
  },
  {
    id: 8,
    name: 'Channel Crown',
    tagline: 'Act I close — Outer Channels accept your claim.',
    art: `${R}diorama/stages/stage8.webp`,
  },
];

const META_UPGRADES: readonly MetaUpgrade[] = [
  {
    id: 's1.lamp',
    name: 'Harbor Lantern',
    blurb: 'A soft amber lamp for the pier rail.',
    cost: 40,
    stage: 1,
    glyph: '✦',
    art: icon('s1_lamp'),
    order: 1,
    place: { left: 14, top: 18, scale: 0.95 },
  },
  {
    id: 's1.vein',
    name: 'Mooring Post',
    blurb: 'Weathered wood with a coil of teal rope.',
    cost: 60,
    stage: 1,
    glyph: '◇',
    art: icon('s1_vein'),
    order: 2,
    place: { left: 72, top: 28, scale: 1.05 },
  },
  {
    id: 's1.cart',
    name: 'Dinghy',
    blurb: 'A small boat tied at the slip — progress you can see.',
    cost: 80,
    stage: 1,
    glyph: '▣',
    art: icon('s1_cart'),
    order: 3,
    place: { left: 38, top: 58, scale: 1.1 },
  },
  {
    id: 's1.banner',
    name: 'Guild Pennant',
    blurb: 'Your claim mark flutters over the pier mouth.',
    cost: 100,
    stage: 1,
    glyph: '⚑',
    art: icon('s1_banner'),
    order: 4,
    place: { left: 78, top: 12, scale: 0.9 },
  },
  {
    id: 's2.prism',
    name: 'Signal Pedestal',
    blurb: 'A resting place for the first Signal Charge.',
    cost: 140,
    stage: 2,
    glyph: '◆',
    art: icon('s2_prism'),
    order: 1,
    place: { left: 44, top: 42, scale: 1.05 },
  },
  {
    id: 's2.pool',
    name: 'Reflection Slip',
    blurb: 'Still water that doubles every lantern glow.',
    cost: 160,
    stage: 2,
    glyph: '○',
    art: icon('s2_pool'),
    order: 2,
    place: { left: 18, top: 62, scale: 1 },
  },
  {
    id: 's2.arch',
    name: 'Market Arch',
    blurb: 'A timber arch into the evening stalls.',
    cost: 180,
    stage: 2,
    glyph: '⌂',
    art: icon('s2_arch'),
    order: 3,
    place: { left: 62, top: 22, scale: 1.15 },
  },
  {
    id: 's2.chorus',
    name: 'Harbor Chimes',
    blurb: 'Soft tones when a cascade hits above.',
    cost: 200,
    stage: 2,
    glyph: '♪',
    art: icon('s2_chorus'),
    order: 4,
    place: { left: 12, top: 16, scale: 0.9 },
  },
  {
    id: 's3.core',
    name: 'Beacon Cradle',
    blurb: 'A spinning Beacon Core sits in the yard.',
    cost: 260,
    stage: 3,
    glyph: '◎',
    art: icon('s3_core'),
    order: 1,
    place: { left: 42, top: 38, scale: 1.1 },
  },
  {
    id: 's3.veins',
    name: 'Lamp Line Network',
    blurb: 'Rope and light crawl across the yard.',
    cost: 280,
    stage: 3,
    glyph: '≡',
    art: icon('s3_veins'),
    order: 2,
    place: { left: 70, top: 24, scale: 1 },
  },
  {
    id: 's3.altar',
    name: 'Festival Altar',
    blurb: 'Where six-match storms are remembered.',
    cost: 300,
    stage: 3,
    glyph: '✶',
    art: icon('s3_altar'),
    order: 3,
    place: { left: 20, top: 48, scale: 1 },
  },
  {
    id: 's3.guardian',
    name: 'Keeper Dog',
    blurb: 'A silent watcher on the lighthouse steps.',
    cost: 320,
    stage: 3,
    glyph: '♜',
    art: icon('s3_guardian'),
    order: 4,
    place: { left: 76, top: 50, scale: 1.05 },
  },
  {
    id: 's4.geode',
    name: 'Grand Lantern',
    blurb: 'Crack the sealed chest — warm light spills out.',
    cost: 400,
    stage: 4,
    glyph: '❋',
    art: icon('s4_geode'),
    order: 1,
    place: { left: 40, top: 40, scale: 1.15 },
  },
  {
    id: 's4.throne',
    name: "Captain's Seat",
    blurb: 'A seat for the one who finished the docks.',
    cost: 450,
    stage: 4,
    glyph: '♛',
    art: icon('s4_throne'),
    order: 2,
    place: { left: 16, top: 52, scale: 1.05 },
  },
  {
    id: 's4.sky',
    name: 'Lantern Canopy',
    blurb: 'The sky fills with a soft night of paper lights.',
    cost: 500,
    stage: 4,
    glyph: '✧',
    art: icon('s4_sky'),
    order: 3,
    place: { left: 68, top: 14, scale: 1.1 },
  },
  // Stage 5 — Outer Channel
  {
    id: 's5.buoy',
    name: 'Channel Buoy',
    blurb: 'A painted buoy marking the Outer Channel mouth.',
    cost: 560,
    stage: 5,
    glyph: '◎',
    art: icon('s5_buoy'),
    order: 1,
    place: { left: 28, top: 42, scale: 1 },
  },
  {
    id: 's5.ledger',
    name: 'Storm Ledger',
    blurb: 'Tide tables and rival flags chalked for the night.',
    cost: 600,
    stage: 5,
    glyph: '≡',
    art: icon('s5_ledger'),
    order: 2,
    place: { left: 62, top: 28, scale: 1.05 },
  },
  {
    id: 's5.slip',
    name: 'Fog Slip',
    blurb: 'A quiet berth where fog sits heavier than rope.',
    cost: 640,
    stage: 5,
    glyph: '○',
    art: icon('s5_slip'),
    order: 3,
    place: { left: 48, top: 62, scale: 1 },
  },
  {
    id: 's5.reply',
    name: 'Beacon Reply',
    blurb: 'A second lamp that answers the lighthouse.',
    cost: 700,
    stage: 5,
    glyph: '✦',
    art: icon('s5_reply'),
    order: 4,
    place: { left: 78, top: 48, scale: 1.1 },
  },
  // Stage 6 — Storm Treaty Quay
  {
    id: 's6.treaty',
    name: 'Treaty Post',
    blurb: 'Where dockhands and fog fleets ink a truce.',
    cost: 780,
    stage: 6,
    glyph: '⚑',
    art: icon('s6_treaty'),
    order: 1,
    place: { left: 36, top: 30, scale: 1.05 },
  },
  {
    id: 's6.fleet',
    name: 'Fog Fleet Line',
    blurb: 'Paper boats wait for the storm to finish its speech.',
    cost: 840,
    stage: 6,
    glyph: '▣',
    art: icon('s6_fleet'),
    order: 2,
    place: { left: 68, top: 55, scale: 1 },
  },
  {
    id: 's6.voice',
    name: 'Tide Voice Bell',
    blurb: 'One ring for every clean Super Chest on the belt.',
    cost: 900,
    stage: 6,
    glyph: '♪',
    art: icon('s6_voice'),
    order: 3,
    place: { left: 22, top: 58, scale: 1.05 },
  },
  {
    id: 's6.close',
    name: 'Quay Seal',
    blurb: 'First Outer Channel seal — more docks still wait beyond.',
    cost: 1000,
    stage: 6,
    glyph: '♛',
    art: icon('s6_close'),
    order: 4,
    place: { left: 52, top: 40, scale: 1.15 },
  },
  // Stage 7 — Quiet Slip Reach
  {
    id: 's7.slip',
    name: 'Quiet Slip',
    blurb: 'A berth where fog sits heavier than rope.',
    cost: 1100,
    stage: 7,
    glyph: '○',
    art: icon('s7_slip'),
    order: 1,
    place: { left: 30, top: 45, scale: 1 },
  },
  {
    id: 's7.quay',
    name: 'Gale Quay Mark',
    blurb: 'Storm paint on timber — mid Act I-C pressure.',
    cost: 1180,
    stage: 7,
    glyph: '⌂',
    art: icon('s7_quay'),
    order: 2,
    place: { left: 68, top: 32, scale: 1.05 },
  },
  {
    id: 's7.fog',
    name: 'Twin Tide Line',
    blurb: 'Two currents that only calm when dual goals clear.',
    cost: 1260,
    stage: 7,
    glyph: '≡',
    art: icon('s7_fog'),
    order: 3,
    place: { left: 48, top: 62, scale: 1 },
  },
  {
    id: 's7.line',
    name: 'Lantern Line',
    blurb: 'A rope of lamps into the last Outer Channel.',
    cost: 1340,
    stage: 7,
    glyph: '✦',
    art: icon('s7_line'),
    order: 4,
    place: { left: 78, top: 55, scale: 1.08 },
  },
  // Stage 8 — Channel Crown (Act I close)
  {
    id: 's8.treaty',
    name: 'Final Treaty',
    blurb: 'Ink dry — fog fleets and dockhands share the night.',
    cost: 1480,
    stage: 8,
    glyph: '⚑',
    art: icon('s8_treaty'),
    order: 1,
    place: { left: 36, top: 28, scale: 1.05 },
  },
  {
    id: 's8.fleet',
    name: 'Horizon Fleet',
    blurb: 'Paper boats for the Channel Crown parade.',
    cost: 1580,
    stage: 8,
    glyph: '▣',
    art: icon('s8_fleet'),
    order: 2,
    place: { left: 70, top: 52, scale: 1 },
  },
  {
    id: 's8.bell',
    name: 'Apex Bell',
    blurb: 'Rings once when you clear the last Outer Channel boss.',
    cost: 1700,
    stage: 8,
    glyph: '♪',
    art: icon('s8_bell'),
    order: 3,
    place: { left: 20, top: 58, scale: 1.05 },
  },
  {
    id: 's8.crown',
    name: 'Channel Crown',
    blurb: 'Act I close — the Outer Channels are yours.',
    cost: 1850,
    stage: 8,
    glyph: '♛',
    art: icon('s8_crown'),
    order: 4,
    place: { left: 52, top: 40, scale: 1.15 },
  },
];

const ALBUM: readonly AlbumCardDef[] = [
  {
    id: 'ember',
    name: 'Coral Lantern',
    glyph: '◆',
    blurb: 'Warm paper light common on the outer pier.',
    rarity: 'common',
    weight: 28,
    atlas: F(0, 0),
    glow: '#e85d4c',
    glowSoft: 'rgba(232, 93, 76, 0.55)',
  },
  {
    id: 'aqua',
    name: 'Blue Shell',
    glyph: '◇',
    blurb: 'Cool shell cut from the tide line.',
    rarity: 'common',
    weight: 26,
    atlas: F(512, 256),
    glow: '#3ec8ff',
    glowSoft: 'rgba(60, 200, 255, 0.55)',
  },
  {
    id: 'jade',
    name: 'Seafoam Tin',
    glyph: '✦',
    blurb: 'Tea tin from the market stalls.',
    rarity: 'common',
    weight: 24,
    atlas: F(896, 128),
    glow: '#7ec8a3',
    glowSoft: 'rgba(126, 200, 163, 0.5)',
  },
  {
    id: 'violet',
    name: 'Violet Fish Tag',
    glyph: '❖',
    blurb: 'Deep hue from the night market.',
    rarity: 'uncommon',
    weight: 14,
    atlas: F(128, 384),
    glow: '#7b6bb0',
    glowSoft: 'rgba(123, 107, 176, 0.55)',
  },
  {
    id: 'solar',
    name: 'Gold Coin Purse',
    glyph: '★',
    blurb: 'A pouch that catches lamp-light.',
    rarity: 'uncommon',
    weight: 12,
    atlas: F(256, 128),
    glow: '#f0a04b',
    glowSoft: 'rgba(240, 160, 75, 0.55)',
  },
  {
    id: 'line',
    name: 'Belt Charge',
    glyph: '═',
    blurb: 'Forged when four align on the sorting belt.',
    rarity: 'uncommon',
    weight: 10,
    atlas: F(128, 0),
    glow: '#ff8a60',
    glowSoft: 'rgba(255, 130, 90, 0.5)',
  },
  {
    id: 'burst',
    name: 'Crate Burst',
    glyph: '◎',
    blurb: 'L/T power stamp for the keepsake album.',
    rarity: 'rare',
    weight: 5,
    atlas: F(0, 128),
    glow: '#ffc060',
    glowSoft: 'rgba(255, 190, 90, 0.65)',
  },
  {
    id: 'prism',
    name: 'Signal Prism',
    glyph: '⬠',
    blurb: 'Five-match rainbow seal of the harbor.',
    rarity: 'rare',
    weight: 4,
    atlas: F(768, 384),
    glow: '#e0b0ff',
    glowSoft: 'rgba(220, 170, 255, 0.65)',
  },
  {
    id: 'warden',
    name: 'Keeper Seal',
    glyph: '⚓',
    blurb: 'A spinning seal from Captain Lumen.',
    rarity: 'rare',
    weight: 3,
    atlas: F(768, 384),
    glow: '#ffe56a',
    glowSoft: 'rgba(255, 230, 100, 0.7)',
  },
];

export const harborTheme: ThemeConfig = {
  id: 'harbor',
  productName: 'Lantern Harbor',
  tagline: 'Sort the belt. Restore the docks. Collect endless keepsakes.',
  storagePrefix: 'harbor',
  saveKey: 'harbor.save',
  ahaKey: 'harbor.ahaDone',
  adShortKey: 'harbor.adShortIndex',
  softCurrencyName: 'Tideglass',
  softCurrencyGlyph: '◌',
  premiumCurrencyName: 'Harbor Tokens',
  metaHubName: 'Harbor Docks',
  metaHubCta: 'Your Docks',
  assetRoot: R,
  bgPath: `${R}bg/harbor-docks-720.webp`,
  genManifestPath: `${R}gen/manifest.json`,
  albumSheet: `${R}gen/crystals@1x.webp`,
  livingCorePath: `${R}gen/living_core.webp`,
  companion: {
    id: 'captain-lumen',
    name: 'Captain Lumen',
    role: 'Harbor keeper',
    art: `${R}characters/captain-lumen.webp`,
    lines: {
      title: [
        'The tide remembers your steps. Sort when ready.',
        'Match, signal, restore — I keep the lanterns lit.',
        'A clear belt feeds the docks. Shall we?',
      ],
      titleFirst: [
        'First light on the pier. Swap four to forge a signal.',
        'Welcome, dockhand. I will show you the belt.',
      ],
      win: [
        'Clean sort! Tideglass drips into the docks.',
        'The stalls hum for you — well done.',
        'Another slip yields. Onward, carefully.',
      ],
      winPerfect: [
        'Three stars — the grand lantern sings. Discovery bonus sealed.',
        'Flawless work. The festival will hear of this.',
      ],
      lose: [
        'The fog closed early. Breathe — lives return.',
        'Almost. The tide is patient; so are we.',
        'Not this path. Try another pass on the belt.',
      ],
      daily: [
        'A daily parcel from the guild. Claim it, friend.',
        'Welcome back. The docks left you a stipend.',
      ],
      cavern: [
        'Place what you can afford — the vista grows with you.',
        'Furnish the open stage. Ghost slots mark what is next.',
      ],
      cavernReady: [
        'You can place a piece right now. Look at the shop below.',
        'Tideglass is ready — seal it into the docks.',
      ],
      geode: [
        'Tap a sealed chest. One hides a richer crack.',
        'Three chests. Trust your choice — I will not spoil it.',
      ],
      geodeResult: [
        'Sparkles for the docks fund!',
        'A fine crack. Bank it and keep sorting.',
        'Jackpot chest! The Keeper is impressed.',
      ],
      coreSpire: [
        'Night Festival — the belt never sleeps under the canopy.',
        'Deep docks. Steady hands. I am with you still.',
      ],
      streak: [
        'The streak holds. Don’t rush the fog.',
        'Heat in the lamp glass — keep the chain clean.',
      ],
    },
  },
  metaStages: META_STAGES,
  metaUpgrades: META_UPGRADES,
  albumCards: ALBUM,
  mapChapters: [
    { roman: 'I', title: 'Pier Lights', depth: 'shallow', minId: 1, maxId: 10 },
    { roman: 'II', title: 'Market Row', depth: 'mid', minId: 11, maxId: 20 },
    { roman: 'III', title: 'Lighthouse Yard', depth: 'deep', minId: 21, maxId: 30 },
    { roman: 'IV', title: 'Night Festival', depth: 'core', minId: 31, maxId: 40 },
    { roman: 'V', title: 'Storm Pier', depth: 'deep', minId: 41, maxId: 50 },
    { roman: 'VI', title: 'Harbor Crown', depth: 'deep', minId: 51, maxId: 60 },
    { roman: 'VII', title: 'Blackwater Docks', depth: 'core', minId: 61, maxId: 70 },
    { roman: 'VIII', title: 'Lantern Deep', depth: 'core', minId: 71, maxId: 80 },
    { roman: 'IX', title: 'Endless Tide', depth: 'core', minId: 81, maxId: 90 },
    { roman: 'X', title: 'Horizon Beacon', depth: 'core', minId: 91, maxId: 100 },
    { roman: 'XI', title: 'Fog Reach', depth: 'deep', minId: 101, maxId: 110 },
    { roman: 'XII', title: 'Outer Buoy', depth: 'deep', minId: 111, maxId: 120 },
    { roman: 'XIII', title: 'Gale Quay', depth: 'core', minId: 121, maxId: 130 },
    { roman: 'XIV', title: 'Lantern Abyss', depth: 'core', minId: 131, maxId: 140 },
    { roman: 'XV', title: 'Harbor Apex', depth: 'core', minId: 141, maxId: 150 },
    // Act I-C Outer Channels (docs/CAMPAIGN_ARC.md XVI–XXX)
    { roman: 'XVI', title: 'Channel Mouth', depth: 'deep', minId: 151, maxId: 160 },
    { roman: 'XVII', title: 'Storm Ledger', depth: 'deep', minId: 161, maxId: 170 },
    { roman: 'XVIII', title: 'Rival Buoy', depth: 'core', minId: 171, maxId: 180 },
    { roman: 'XIX', title: 'Fog Choir', depth: 'core', minId: 181, maxId: 190 },
    { roman: 'XX', title: 'Outer Road', depth: 'core', minId: 191, maxId: 200 },
    { roman: 'XXI', title: 'Quiet Slip', depth: 'deep', minId: 201, maxId: 210 },
    { roman: 'XXII', title: 'Twin Tide', depth: 'deep', minId: 211, maxId: 220 },
    { roman: 'XXIII', title: 'Blackwater Reach', depth: 'core', minId: 221, maxId: 230 },
    { roman: 'XXIV', title: 'Beacon Reply', depth: 'core', minId: 231, maxId: 240 },
    { roman: 'XXV', title: 'Apex Approach', depth: 'core', minId: 241, maxId: 250 },
    { roman: 'XXVI', title: 'Treaty Draft', depth: 'core', minId: 251, maxId: 260 },
    { roman: 'XXVII', title: 'Festival Storm', depth: 'core', minId: 261, maxId: 270 },
    { roman: 'XXVIII', title: 'Tide Voice', depth: 'core', minId: 271, maxId: 280 },
    { roman: 'XXIX', title: 'Last Quay', depth: 'core', minId: 281, maxId: 290 },
    { roman: 'XXX', title: 'Channel Close', depth: 'core', minId: 291, maxId: 300 },
  ],
  storeCopy: {
    'shards.pocket': {
      name: 'Pocket Tokens',
      blurb: 'A small pouch of harbor tokens.',
    },
    'shards.hoard': {
      name: "Dockmaster's Hoard",
      blurb: 'Five times the tokens for five times the price — and then some.',
    },
    'shards.vault': {
      name: 'Festival Vault',
      blurb: 'A thousand tokens, plus a full set of boosters to keep the belt moving.',
    },
    'bundle.starter': {
      name: 'First Tide Bundle',
      blurb: 'One time only: tokens, boosters and a full set of lives at a steep discount.',
    },
    'ads.remove': {
      name: 'Clear Skies',
      blurb: 'Permanently removes simulated interstitials.',
    },
    'ads.pass7': {
      name: 'Clear Skies · 7 Days',
      blurb: 'Ethical convenience: no interstitial Shorts for a week. Stacks from purchase time.',
    },
    'ads.pass30': {
      name: 'Clear Skies · 30 Days',
      blurb: 'Player-friendly month pass for ad-free dock runs. No hard paywall.',
    },
    'ease.comfort': {
      name: 'Comfort Tools',
      blurb: 'Ease of play: longer auto-hints, soft belt framing, and one free reshuffle per level. No dark timers.',
    },
  },
  palette: {
    ember: '#e85d4c',
    aurum: '#c47a2e',
    solar: '#f0a04b',
    verdant: '#2a8f6a',
    tidal: '#2a8f9a',
    void: '#7b6bb0',
  },
  labels: {
    powerCrystal: 'Signal Charge',
    livingCore: 'Beacon Core',
    conveyorActive: 'Sorting belt active',
    slowBelt: 'Slow the belt',
    idleClaim: 'Docks idle',
    bonusCrack: 'Chest crack',
    eventName: 'Tide Rush',
    dailyGoal: 'Daily dock run',
    albumTitle: 'Keepsake Album',
    playCta: 'SORT',
    mapTitle: 'The Harbor',
  },
  cssVars: {
    '--bg': '#0b1c2e',
    '--panel': '#122838',
    '--panel-2': '#1a3548',
    '--panel-edge': '#2a8f9a',
    '--panel-edge-hi': '#f0a04b',
    '--text': '#f4efe6',
    '--muted': '#a8c0c8',
    '--accent': '#5ec8d4',
    '--accent-deep': '#1a6f8a',
    '--gold': '#f0a04b',
    '--gold-deep': '#c47a08',
    '--danger': '#e85d4c',
    '--ok': '#7ec8a3',
    '--sim': '#ff9a62',
    /* Tidepop = logo letters only. Numbers/UI never hit Tidepop first.
       Fredoka statics (local) + ScreenTechno digits + system sans. */
    '--font-title': '"Tidepop", "Fredoka", "ScreenTechno", system-ui, sans-serif',
    '--font-display': '"Fredoka", "ScreenTechno", system-ui, sans-serif',
    '--font-body': '"Fredoka", "Nunito", "Segoe UI", system-ui, sans-serif',
    '--map-home-bg': 'linear-gradient(180deg, rgba(20, 36, 52, 0.92), rgba(10, 18, 28, 0.95))',
    '--map-home-edge': 'rgba(94, 200, 212, 0.28)',
    '--place-scrim':
      'linear-gradient(90deg, rgba(6, 14, 22, 0.88) 0%, rgba(6, 14, 22, 0.45) 55%, rgba(6, 14, 22, 0.2) 100%)',
  },
  bonusCrackName: 'Chest',
  bonusCrackArt: 'themes/harbor/ui/geode_vein.webp',
  versionLabel: 'Lantern Harbor v1.0.1 · 300 levels · Departure Bay Digital',
  powerNames: {
    line: 'Belt Rift',
    burst: 'Crate Burst',
    prism: 'Signal Prism',
    /** 6+ match Super Chest — octopus pulls shells with tentacles and eats them. */
    supernova: 'Super Chest',
  },
  comboLabels: {
    'line+line': 'Twin Tides',
    'line+burst': 'Belt Bloom',
    'burst+burst': 'Harbor Shockwave',
    'line+prism': 'Lantern Seams',
    'burst+prism': 'Lantern Bloom',
    'prism+prism': 'Fog Collapse',
    'line+supernova': 'Tide Rift',
    'burst+supernova': 'Crate Feast',
    'prism+supernova': 'Signal Feast',
    'supernova+supernova': 'Double Kraken',
  },
  event: {
    idPrefix: 'tide-rush',
    name: 'Tide Rush',
    tagline: 'Clear docks for personal milestones · soft league for flavour',
    milestones: [
      { at: 3, label: 'First slip', essence: 20, shards: 5 },
      { at: 8, label: 'Deep current', essence: 35, shards: 10 },
      { at: 15, label: 'Market clear', essence: 50, shards: 15 },
      { at: 25, label: 'Lighthouse push', essence: 80, shards: 25 },
    ],
    league: ['Harbor Elite', 'Tide Patrol', 'Dockhands'],
  },
  // No mine placement reel — still-image ceremony over stage art.
  placeCeremony: {
    webm: '',
    mp4: '',
    caption: 'Placed on the docks',
  },
};
