/**
 * Lantern Harbor — cozy coastal theme pack (sibling product).
 * All art under public/themes/harbor/. Engine color ids unchanged.
 */

import type { ThemeConfig } from './types';
import type { AlbumCardDef } from '@economy/album';
import type { MetaStage, MetaUpgrade } from '@economy/meta';

const R = 'themes/harbor/';
const icon = (file: string) => `${R}diorama/icons/${file}.webp`;

const F = (x: number, y: number) =>
  ({ x, y, w: 128, h: 128 }) as const;

const META_STAGES: readonly MetaStage[] = [
  {
    id: 1,
    name: 'Pier Lights',
    tagline: 'Light the first lanterns and claim the pier.',
    art: `${R}diorama/stages/stage1.webp`,
  },
  {
    id: 2,
    name: 'Market Row',
    tagline: 'Stalls hum with tea, crates, and evening trade.',
    art: `${R}diorama/stages/stage2.webp`,
  },
  {
    id: 3,
    name: 'Lighthouse Yard',
    tagline: 'Where the beacon still remembers the fog.',
    art: `${R}diorama/stages/stage3.webp`,
  },
  {
    id: 4,
    name: 'Night Festival',
    tagline: 'A canopy of lanterns only the stubborn reach.',
    art: `${R}diorama/stages/stage4.webp`,
  },
];

const META_UPGRADES: readonly MetaUpgrade[] = [
  {
    id: 's1.lamp',
    name: 'Harbor Lantern',
    blurb: 'A soft amber lamp for the pier rail.',
    cost: 40,
    stage: 1,
    glyph: '✦',
    art: icon('s1_lamp'),
    order: 1,
    place: { left: 14, top: 18, scale: 0.95 },
  },
  {
    id: 's1.vein',
    name: 'Mooring Post',
    blurb: 'Weathered wood with a coil of teal rope.',
    cost: 60,
    stage: 1,
    glyph: '◇',
    art: icon('s1_vein'),
    order: 2,
    place: { left: 72, top: 28, scale: 1.05 },
  },
  {
    id: 's1.cart',
    name: 'Dinghy',
    blurb: 'A small boat tied at the slip — progress you can see.',
    cost: 80,
    stage: 1,
    glyph: '▣',
    art: icon('s1_cart'),
    order: 3,
    place: { left: 38, top: 58, scale: 1.1 },
  },
  {
    id: 's1.banner',
    name: 'Guild Pennant',
    blurb: 'Your claim mark flutters over the pier mouth.',
    cost: 100,
    stage: 1,
    glyph: '⚑',
    art: icon('s1_banner'),
    order: 4,
    place: { left: 78, top: 12, scale: 0.9 },
  },
  {
    id: 's2.prism',
    name: 'Signal Pedestal',
    blurb: 'A resting place for the first Signal Charge.',
    cost: 140,
    stage: 2,
    glyph: '◆',
    art: icon('s2_prism'),
    order: 1,
    place: { left: 44, top: 42, scale: 1.05 },
  },
  {
    id: 's2.pool',
    name: 'Reflection Slip',
    blurb: 'Still water that doubles every lantern glow.',
    cost: 160,
    stage: 2,
    glyph: '○',
    art: icon('s2_pool'),
    order: 2,
    place: { left: 18, top: 62, scale: 1 },
  },
  {
    id: 's2.arch',
    name: 'Market Arch',
    blurb: 'A timber arch into the evening stalls.',
    cost: 180,
    stage: 2,
    glyph: '⌂',
    art: icon('s2_arch'),
    order: 3,
    place: { left: 62, top: 22, scale: 1.15 },
  },
  {
    id: 's2.chorus',
    name: 'Harbor Chimes',
    blurb: 'Soft tones when a cascade hits above.',
    cost: 200,
    stage: 2,
    glyph: '♪',
    art: icon('s2_chorus'),
    order: 4,
    place: { left: 12, top: 16, scale: 0.9 },
  },
  {
    id: 's3.core',
    name: 'Beacon Cradle',
    blurb: 'A spinning Beacon Core sits in the yard.',
    cost: 260,
    stage: 3,
    glyph: '◎',
    art: icon('s3_core'),
    order: 1,
    place: { left: 42, top: 38, scale: 1.1 },
  },
  {
    id: 's3.veins',
    name: 'Lamp Line Network',
    blurb: 'Rope and light crawl across the yard.',
    cost: 280,
    stage: 3,
    glyph: '≡',
    art: icon('s3_veins'),
    order: 2,
    place: { left: 70, top: 24, scale: 1 },
  },
  {
    id: 's3.altar',
    name: 'Festival Altar',
    blurb: 'Where six-match storms are remembered.',
    cost: 300,
    stage: 3,
    glyph: '✶',
    art: icon('s3_altar'),
    order: 3,
    place: { left: 20, top: 48, scale: 1 },
  },
  {
    id: 's3.guardian',
    name: 'Keeper Dog',
    blurb: 'A silent watcher on the lighthouse steps.',
    cost: 320,
    stage: 3,
    glyph: '♜',
    art: icon('s3_guardian'),
    order: 4,
    place: { left: 76, top: 50, scale: 1.05 },
  },
  {
    id: 's4.geode',
    name: 'Grand Lantern',
    blurb: 'Crack the sealed chest — warm light spills out.',
    cost: 400,
    stage: 4,
    glyph: '❋',
    art: icon('s4_geode'),
    order: 1,
    place: { left: 40, top: 40, scale: 1.15 },
  },
  {
    id: 's4.throne',
    name: "Captain's Seat",
    blurb: 'A seat for the one who finished the docks.',
    cost: 450,
    stage: 4,
    glyph: '♛',
    art: icon('s4_throne'),
    order: 2,
    place: { left: 16, top: 52, scale: 1.05 },
  },
  {
    id: 's4.sky',
    name: 'Lantern Canopy',
    blurb: 'The sky fills with a soft night of paper lights.',
    cost: 500,
    stage: 4,
    glyph: '✧',
    art: icon('s4_sky'),
    order: 3,
    place: { left: 68, top: 14, scale: 1.1 },
  },
];

const ALBUM: readonly AlbumCardDef[] = [
  {
    id: 'ember',
    name: 'Coral Lantern',
    glyph: '◆',
    blurb: 'Warm paper light common on the outer pier.',
    rarity: 'common',
    weight: 28,
    atlas: F(0, 0),
    glow: '#e85d4c',
    glowSoft: 'rgba(232, 93, 76, 0.55)',
  },
  {
    id: 'aqua',
    name: 'Blue Shell',
    glyph: '◇',
    blurb: 'Cool shell cut from the tide line.',
    rarity: 'common',
    weight: 26,
    atlas: F(512, 256),
    glow: '#3ec8ff',
    glowSoft: 'rgba(60, 200, 255, 0.55)',
  },
  {
    id: 'jade',
    name: 'Seafoam Tin',
    glyph: '✦',
    blurb: 'Tea tin from the market stalls.',
    rarity: 'common',
    weight: 24,
    atlas: F(896, 128),
    glow: '#7ec8a3',
    glowSoft: 'rgba(126, 200, 163, 0.5)',
  },
  {
    id: 'violet',
    name: 'Violet Fish Tag',
    glyph: '❖',
    blurb: 'Deep hue from the night market.',
    rarity: 'uncommon',
    weight: 14,
    atlas: F(128, 384),
    glow: '#7b6bb0',
    glowSoft: 'rgba(123, 107, 176, 0.55)',
  },
  {
    id: 'solar',
    name: 'Gold Coin Purse',
    glyph: '★',
    blurb: 'A pouch that catches lamp-light.',
    rarity: 'uncommon',
    weight: 12,
    atlas: F(256, 128),
    glow: '#f0a04b',
    glowSoft: 'rgba(240, 160, 75, 0.55)',
  },
  {
    id: 'line',
    name: 'Belt Charge',
    glyph: '═',
    blurb: 'Forged when four align on the sorting belt.',
    rarity: 'uncommon',
    weight: 10,
    atlas: F(128, 0),
    glow: '#ff8a60',
    glowSoft: 'rgba(255, 130, 90, 0.5)',
  },
  {
    id: 'burst',
    name: 'Crate Burst',
    glyph: '◎',
    blurb: 'L/T power stamp for the keepsake album.',
    rarity: 'rare',
    weight: 5,
    atlas: F(0, 128),
    glow: '#ffc060',
    glowSoft: 'rgba(255, 190, 90, 0.65)',
  },
  {
    id: 'prism',
    name: 'Signal Prism',
    glyph: '⬠',
    blurb: 'Five-match rainbow seal of the harbor.',
    rarity: 'rare',
    weight: 4,
    atlas: F(768, 384),
    glow: '#e0b0ff',
    glowSoft: 'rgba(220, 170, 255, 0.65)',
  },
  {
    id: 'warden',
    name: 'Keeper Seal',
    glyph: '⚓',
    blurb: 'A spinning seal from Captain Lumen.',
    rarity: 'rare',
    weight: 3,
    atlas: F(768, 384),
    glow: '#ffe56a',
    glowSoft: 'rgba(255, 230, 100, 0.7)',
  },
];

export const harborTheme: ThemeConfig = {
  id: 'harbor',
  productName: 'Lantern Harbor',
  tagline: 'Sort the belt. Restore the docks. Collect endless keepsakes.',
  storagePrefix: 'harbor',
  saveKey: 'harbor.save',
  ahaKey: 'harbor.ahaDone',
  adShortKey: 'harbor.adShortIndex',
  softCurrencyName: 'Tideglass',
  softCurrencyGlyph: '◌',
  premiumCurrencyName: 'Harbor Tokens',
  metaHubName: 'Harbor Docks',
  metaHubCta: 'Your Docks',
  assetRoot: R,
  bgPath: `${R}bg/harbor-docks-720.webp`,
  genManifestPath: `${R}gen/manifest.json`,
  albumSheet: `${R}gen/crystals@1x.webp`,
  livingCorePath: `${R}gen/living_core.webp`,
  companion: {
    id: 'captain-lumen',
    name: 'Captain Lumen',
    role: 'Harbor keeper',
    art: `${R}characters/captain-lumen.webp`,
    lines: {
      title: [
        'The tide remembers your steps. Sort when ready.',
        'Match, signal, restore — I keep the lanterns lit.',
        'A clear belt feeds the docks. Shall we?',
      ],
      titleFirst: [
        'First light on the pier. Swap four to forge a signal.',
        'Welcome, dockhand. I will show you the belt.',
      ],
      win: [
        'Clean sort! Tideglass drips into the docks.',
        'The stalls hum for you — well done.',
        'Another slip yields. Onward, carefully.',
      ],
      winPerfect: [
        'Three stars — the grand lantern sings. Discovery bonus sealed.',
        'Flawless work. The festival will hear of this.',
      ],
      lose: [
        'The fog closed early. Breathe — lives return.',
        'Almost. The tide is patient; so are we.',
        'Not this path. Try another pass on the belt.',
      ],
      daily: [
        'A daily parcel from the guild. Claim it, friend.',
        'Welcome back. The docks left you a stipend.',
      ],
      cavern: [
        'Place what you can afford — the vista grows with you.',
        'Furnish the open stage. Ghost slots mark what is next.',
      ],
      cavernReady: [
        'You can place a piece right now. Look at the shop below.',
        'Tideglass is ready — seal it into the docks.',
      ],
      geode: [
        'Tap a sealed chest. One hides a richer crack.',
        'Three chests. Trust your choice — I will not spoil it.',
      ],
      geodeResult: [
        'Sparkles for the docks fund!',
        'A fine crack. Bank it and keep sorting.',
        'Jackpot chest! The Keeper is impressed.',
      ],
      coreSpire: [
        'Night Festival — the belt never sleeps under the canopy.',
        'Deep docks. Steady hands. I am with you still.',
      ],
      streak: [
        'The streak holds. Don’t rush the fog.',
        'Heat in the lamp glass — keep the chain clean.',
      ],
    },
  },
  metaStages: META_STAGES,
  metaUpgrades: META_UPGRADES,
  albumCards: ALBUM,
  mapChapters: [
    { roman: 'I', title: 'Pier Lights', depth: 'shallow', minId: 1, maxId: 10 },
    { roman: 'II', title: 'Market Row', depth: 'mid', minId: 11, maxId: 20 },
    { roman: 'III', title: 'Lighthouse Yard', depth: 'deep', minId: 21, maxId: 30 },
    { roman: 'IV', title: 'Night Festival', depth: 'core', minId: 31, maxId: 999 },
  ],
  storeCopy: {
    'shards.pocket': {
      name: 'Pocket Tokens',
      blurb: 'A small pouch of harbor tokens.',
    },
    'shards.hoard': {
      name: "Dockmaster's Hoard",
      blurb: 'Five times the tokens for five times the price — and then some.',
    },
    'shards.vault': {
      name: 'Festival Vault',
      blurb: 'A thousand tokens, plus a full set of boosters to keep the belt moving.',
    },
    'bundle.starter': {
      name: 'First Tide Bundle',
      blurb: 'One time only: tokens, boosters and a full set of lives at a steep discount.',
    },
    'ads.remove': {
      name: 'Clear Skies',
      blurb: 'Permanently removes simulated interstitials.',
    },
    'ads.pass7': {
      name: 'Clear Skies · 7 Days',
      blurb: 'Ethical convenience: no interstitial Shorts for a week. Stacks from purchase time.',
    },
    'ads.pass30': {
      name: 'Clear Skies · 30 Days',
      blurb: 'Player-friendly month pass for ad-free dock runs. No hard paywall.',
    },
    'ease.comfort': {
      name: 'Comfort Tools',
      blurb: 'Ease of play: longer auto-hints, soft belt framing, and one free reshuffle per level. No dark timers.',
    },
  },
  palette: {
    ember: '#e85d4c',
    aurum: '#c47a2e',
    solar: '#f0a04b',
    verdant: '#2a8f6a',
    tidal: '#2a8f9a',
    void: '#7b6bb0',
  },
  labels: {
    powerCrystal: 'Signal Charge',
    livingCore: 'Beacon Core',
    conveyorActive: 'Sorting belt active',
    slowBelt: 'Slow the belt',
    idleClaim: 'Docks idle',
    bonusCrack: 'Chest crack',
    eventName: 'Tide Rush',
    dailyGoal: 'Daily dock run',
    albumTitle: 'Keepsake Album',
    playCta: 'SORT',
    mapTitle: 'The Harbor',
  },
  cssVars: {
    '--bg': '#0b1c2e',
    '--panel': '#122838',
    '--panel-2': '#1a3548',
    '--panel-edge': '#2a8f9a',
    '--panel-edge-hi': '#f0a04b',
    '--text': '#f4efe6',
    '--muted': '#a8c0c8',
    '--accent': '#5ec8d4',
    '--accent-deep': '#1a6f8a',
    '--gold': '#f0a04b',
    '--gold-deep': '#c47a08',
    '--danger': '#e85d4c',
    '--ok': '#7ec8a3',
    '--sim': '#ff9a62',
  },
  bonusCrackName: 'Chest',
  versionLabel: 'Lantern Harbor v0.1.0 · portfolio demo',
};
